In [1]:
import pandas as pd

In [2]:
ds = pd.read_csv("Placement.csv")

In [3]:
#ds.info()

In [4]:
from Univariate import Univariate
Qual,Quan = Univariate.QualQuan(ds)

In [5]:
Qual

['gender',
 'ssc_b',
 'hsc_b',
 'hsc_s',
 'degree_t',
 'workex',
 'specialisation',
 'status']

In [6]:
Quan

['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']

# Central Tendency

In [7]:
ds.describe()

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
count,215.000000,215.000000,215.000000,215.000000,215.000000,215.000000,148.000000
mean,108.000000,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
std,62.209324,10.827205,10.897509,7.358743,13.275956,5.833385,93457.452420
min,1.000000,40.890000,37.000000,50.000000,50.000000,51.210000,200000.000000
25%,54.500000,60.600000,60.900000,61.000000,60.000000,57.945000,240000.000000
50%,108.000000,67.000000,65.000000,66.000000,71.000000,62.000000,265000.000000
75%,161.500000,75.700000,73.000000,72.000000,83.500000,66.255000,300000.000000
max,215.000000,89.400000,97.700000,91.000000,98.000000,77.890000,940000.000000

In [8]:
ds["ssc_p"].mean() # Average Value

np.float64(67.30339534883721)

In [9]:
ds["ssc_p"].median() # Center Value

np.float64(67.0)

In [10]:
ds["ssc_p"].mode() # Repeated value

0    62.0
Name: ssc_p, dtype: float64

In [11]:
ds["ssc_p"].mode() [0]# Repeated value

np.float64(62.0)

In [12]:
descriptive=pd.DataFrame(index=["Mean","Median","Mode"],columns=Quan)

In [13]:
descriptive

       sl_no ssc_p hsc_p degree_p etest_p mba_p salary
Mean     NaN   NaN   NaN      NaN     NaN   NaN    NaN
Median   NaN   NaN   NaN      NaN     NaN   NaN    NaN
Mode     NaN   NaN   NaN      NaN     NaN   NaN    NaN

In [14]:
descriptive.loc["ssc_p","Mode"]=0

In [15]:
descriptive=pd.DataFrame(index=["Mean","Median","Mode"],columns=Quan)
for columnName in Quan:
    descriptive.loc["Mean",columnName]=ds[columnName].mean()
    descriptive.loc["Median",columnName]=ds[columnName].median()
    descriptive.loc["Mode",columnName]=ds[columnName].mode()[0]

In [16]:
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0

# Percentile

In [17]:
import numpy as np

In [18]:
np.percentile(ds["ssc_p"],25)

np.float64(60.599999999999994)

In [19]:
descriptive=pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%","Q3:75%","99%","Q4:100","IQR","1.5 Rule","Lesser Quartile","Greater Quartile","Min Value","Max Value"],columns=Quan)
for columnName in Quan:
    descriptive.loc["Mean",columnName]=ds[columnName].mean()
    descriptive.loc["Median",columnName]=ds[columnName].median()
    descriptive.loc["Mode",columnName]=ds[columnName].mode()[0]
    descriptive.loc["Q1:25%",columnName]=ds.describe()[columnName]["25%"]
    descriptive.loc["Q2:50%",columnName]=ds.describe()[columnName]["50%"]
    descriptive.loc["Q3:75%",columnName]=ds.describe()[columnName]["75%"]
    descriptive.loc["99%",columnName]=np.percentile(ds[columnName],99)
    descriptive.loc["Q4:100",columnName]=ds.describe()[columnName]["max"]
    descriptive.loc["IQR",columnName]=descriptive.loc["Q3:75%",columnName] - descriptive.loc["Q1:25%",columnName]
    descriptive.loc["1.5 Rule",columnName]= 1.5 * descriptive.loc["IQR",columnName]
    descriptive.loc["Lesser Quartile",columnName]= ds.describe()[columnName]["25%"] - descriptive.loc["1.5 Rule",columnName]
    descriptive.loc["Greater Quartile",columnName]=descriptive.loc["Q3:75%",columnName] + descriptive.loc["1.5 Rule",columnName]
    descriptive.loc["Min Value",columnName]=ds[columnName].min()
    descriptive.loc["Max Value",columnName]=ds[columnName].max()

In [20]:
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
99%,212.86,87.0,91.86,83.86,97.0,76.1142,NaN
Q4:100,215.0,89.4,97.7,91.0,98.0,77.89,940000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5 Rule,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
Lesser Quartile,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
Greater Quartile,322.0,98.35,91.15,88.5,118.75,78.72,390000.0
Min Value,1,40.89,37.0,50.0,50.0,51.21,200000.0
Max Value,215,89.4,97.7,91.0,98.0,77.89,940000.0

# Identify the outliers

In [21]:
lesser,greater = [], []

In [22]:
for columnName in Quan:
    if (descriptive.loc["Lesser Quartile",columnName] > descriptive.loc["Min Value",columnName]):
        lesser.append(columnName)
    if (descriptive.loc["Greater Quartile",columnName] < descriptive.loc["Max Value",columnName]):
        greater.append(columnName)

In [23]:
lesser

['hsc_p']

In [24]:
greater

['hsc_p', 'degree_p', 'salary']

# Replace the Outlier

In [44]:
for column in lesser:
    ds[column][ds[column]<descriptive[column]["Lesser Quartile"]]=descriptive[column]["Lesser Quartile"]
for column in greater:
    ds[column][ds[column]>descriptive[column]["Greater Quartile"]]=descriptive[column]["Greater Quartile"]

C:\Users\1309048\AppData\Local\Temp\ipykernel_10428\1381443171.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  ds[column][ds[column]<descriptive[column]["Lesser Quartile"]]=descriptive[column]["Lesser Quartile"]
C:\Users\1309048\AppData\Local\Temp\ipykernel_10428\1381443171.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds[column][ds[column]<descriptive[column]["Lesser Quartile"]]=descriptive[column]["Lesser Quartile"]
C:\Users\1309048\AppData\Local\Temp\ipykernel_10428\1381443171.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  ds[column][ds[column]>descriptive[column]["Greater Quartile"]]=descriptive[column]["Greater Quartile"]
C:\Users\1309048\AppData\Local\Temp\ipykernel_10428\1381443171.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds[column][ds[column]>descriptive[column]["Greater Quartile"]]=descriptive[column]["Greater Quartile"]
C:\Users\1309048\AppData\Local\Temp\ipykernel_10428\1381443171.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  ds[column][ds[column]>descriptive[column]["Greater Quartile"]]=descriptive[column]["Greater Quartile"]
C:\Users\1309048\AppData\Local\Temp\ipykernel_10428\1381443171.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds[column][ds[column]>descriptive[column]["Greater Quartile"]]=descriptive[column]["Greater Quartile"]
C:\Users\1309048\AppData\Local\Temp\ipykernel_10428\1381443171.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  ds[column][ds[column]>descriptive[column]["Greater Quartile"]]=descriptive[column]["Greater Quartile"]
C:\Users\1309048\AppData\Local\Temp\ipykernel_10428\1381443171.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds[column][ds[column]>descriptive[column]["Greater Quartile"]]=descriptive[column]["Greater Quartile"]

In [45]:
'''
for column in lesser:
    ds.loc[ds[column]<descriptive.loc["Lesser Quartile",column],column]=descriptive.loc["Lesser Quartile",column]
for column in greater:
     ds.loc[ds[column]>descriptive.loc["Greater Quartile",column],column]=descriptive.loc["Greater Quartile",column]
'''

'\nfor column in lesser:\n    ds.loc[ds[column]<descriptive.loc["Lesser Quartile",column],column]=descriptive.loc["Lesser Quartile",column]\nfor column in greater:\n     ds.loc[ds[column]>descriptive.loc["Greater Quartile",column],column]=descriptive.loc["Greater Quartile",column]\n'

In [46]:
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
99%,212.86,87.0,91.86,83.86,97.0,76.1142,NaN
Q4:100,215.0,89.4,97.7,91.0,98.0,77.89,940000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5 Rule,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
Lesser Quartile,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
Greater Quartile,322.0,98.35,91.15,88.5,118.75,78.72,390000.0
Min Value,1,40.89,37.0,50.0,50.0,51.21,200000.0
Max Value,215,89.4,97.7,91.0,98.0,77.89,940000.0

In [47]:
lesser,greater = [], []

In [48]:
for columnName in Quan:
    if (descriptive.loc["Lesser Quartile",columnName] > descriptive.loc["Min Value",columnName]):
        lesser.append(columnName)
    if (descriptive.loc["Greater Quartile",columnName] < descriptive.loc["Max Value",columnName]):
        greater.append(columnName)

In [49]:
lesser

['hsc_p']

In [50]:
greater

['hsc_p', 'degree_p', 'salary']